feat: диплом (часть 1 из 3)
DanSBol/java-explore-with-me pull request #1
Opened 2024-08-05 15:30 UTC by DanSBol

2024-08-06 11:58 UTC, ErkinKasymaliev requested changes
привет, оставил комменты

2024-08-06 11:58 UTC, ErkinKasymaliev commented on stats/stats-dto/src/main/java/ru/practicum/ewm/dto/stats/ShortStatsDto.java
> +@Getter
все кроме @Builder уже есть в аннотации @Data, удалите лишние аннотациии

2024-08-06 11:58 UTC, ErkinKasymaliev commented on stats/stats-dto/src/main/java/ru/practicum/ewm/dto/stats/StatsDto.java
> +@Getter
все кроме @Builder уже есть в аннотации @Data, удалите лишние аннотациии

2024-08-06 11:58 UTC, ErkinKasymaliev commented on stats/stats-server/src/main/java/ru/practicum/ewm/config/PersistenceConfig.java
> +public class PersistenceConfig {
а просто в application.properties если прописать? или вы тут типа узкую настройку делаете?

2024-08-06 11:58 UTC, ErkinKasymaliev commented on stats/stats-server/src/main/java/ru/practicum/ewm/stats/StatsController.java
> +@RequestMapping
лишняя аннотация

2024-08-06 11:58 UTC, ErkinKasymaliev commented on stats/stats-server/src/main/java/ru/practicum/ewm/stats/StatsServiceImpl.java
> +@Transactional
лишняя

2024-08-06 13:53 UTC, DanSBol commented on stats/stats-dto/src/main/java/ru/practicum/ewm/dto/stats/ShortStatsDto.java
> +@Getter
Поправил

2024-08-06 13:53 UTC, DanSBol commented on stats/stats-dto/src/main/java/ru/practicum/ewm/dto/stats/StatsDto.java
> +@Getter
Поправил

2024-08-06 14:14 UTC, DanSBol commented on stats/stats-server/src/main/java/ru/practicum/ewm/stats/StatsController.java
> +@RequestMapping
Удалил @RequestMapping

2024-08-06 14:19 UTC, DanSBol commented on stats/stats-server/src/main/java/ru/practicum/ewm/stats/StatsServiceImpl.java
> +@Transactional
Удалил @Transactional

2024-08-06 14:31 UTC, DanSBol commented on stats/stats-server/src/main/java/ru/practicum/ewm/config/PersistenceConfig.java
> +public class PersistenceConfig {
В Яндекс Практикум в предложенных шаблонах (см. [пример](https://github.com/praktikum-java/module4_spring_without_boot/blob/containers/src/main/java/ru/practicum/config/PersistenceConfig.java)) и в моих ранее сданных проектах (см. [пример](https://github.com/DanSBol/java-shareit/blob/add-docker/server/src/main/java/ru/practicum/shareit/config/PersistenceConfig.java)) именно такой формат PersistenceConfig. Я это использую, как наиболее корректный шаблон. Прошу конкретику, что поправить, я поправлю...

2024-08-07 12:23 UTC, ErkinKasymaliev approved these changes
привет, работа принята

2024-08-07 13:37 UTC, merged