feat: диплом
DanSBol/java-explore-with-me pull request #11
Opened 2024-08-20 14:57 UTC by DanSBol

- часть 2 из 3 (main сервис)
- часть 3 из 3 (доп. функционал рейтингов)

2024-08-22 10:28 UTC, ErkinKasymaliev requested changes
привет, отписал.
Основные замечание:
1) Для инжекта используйте @RequiredArgsConstructor;
2) не лепите @RequiredArgsConstructor и @AllArgsConstructor
3) в сервисах используйте @Transactional над методами, которые записывают или удаляют из бд
4) пожалуйста без вложенных классов

2024-08-22 10:28 UTC, ErkinKasymaliev commented on ewm-service/src/main/java/ru/practicum/explore/main/category/controller/CategoryAdminController.java
> +    public CategoryAdminController(CategoryService categoryService) {
давайте везде вместо конструктора использовать  @RequiredArgsConstructor над классом для инжектинга.

2024-08-22 10:28 UTC, ErkinKasymaliev commented on ewm-service/src/main/java/ru/practicum/explore/main/category/controller/CategoryAdminController.java
> +        return new ResponseEntity<>(true, HttpStatus.NO_CONTENT);
HttpStatus.Delete можно использовать

2024-08-22 10:28 UTC, ErkinKasymaliev commented on ewm-service/src/main/java/ru/practicum/explore/main/compilation/service/CompilationService.java
> +@AllArgsConstructor
@RequiredArgsConstructor

2024-08-22 10:28 UTC, ErkinKasymaliev commented on ewm-service/src/main/java/ru/practicum/explore/main/compilation/service/CompilationService.java
> +    public CompilationDto createCompilation(NewCompilationDto newCompilationDto) {
желательно над методами, которые делают операции записи/удаление в бд, ставить аннотацию @Transactional

2024-08-22 10:28 UTC, ErkinKasymaliev commented on ewm-service/src/main/java/ru/practicum/explore/main/event/dto/UpdateEventAdminRequest.java
> +    public enum State {
в отдельный класс

2024-08-22 10:28 UTC, ErkinKasymaliev commented on ewm-service/src/main/java/ru/practicum/explore/main/event/dto/UpdateEventUserRequest.java
> +    public enum State {
в отдельный класс

2024-08-22 10:28 UTC, ErkinKasymaliev commented on ewm-service/src/main/java/ru/practicum/explore/main/event/model/Event.java
> +    public enum State {
в отдельный класс

2024-08-22 10:28 UTC, ErkinKasymaliev commented on ewm-service/src/main/java/ru/practicum/explore/main/event/service/EventService.java
> +    public EventService(EventRepository eventRepository,
вместо конструктора используйте аннотацию @RequiredArgsConstructor

2024-08-22 10:28 UTC, ErkinKasymaliev commented on ewm-service/src/main/java/ru/practicum/explore/main/exceptions/NotFoundException.java
> +    public enum NotFoundType {
в отдельный класс

2024-08-22 10:28 UTC, ErkinKasymaliev commented on ewm-service/src/main/java/ru/practicum/explore/main/rating/model/Rating.java
> +    public static class RatingId implements Serializable {
в отдельный класс

2024-08-22 10:28 UTC, ErkinKasymaliev commented on ewm-service/src/main/java/ru/practicum/explore/main/request/model/Request.java
> +@RequiredArgsConstructor
лишняя аннотация

2024-08-22 11:03 UTC, DanSBol commented on ewm-service/src/main/java/ru/practicum/explore/main/category/controller/CategoryAdminController.java
> +    public CategoryAdminController(CategoryService categoryService) {
Поправил

2024-08-22 11:09 UTC, DanSBol commented on ewm-service/src/main/java/ru/practicum/explore/main/category/controller/CategoryAdminController.java
> +        return new ResponseEntity<>(true, HttpStatus.NO_CONTENT);
Я использую пакет org.springframework.http.HttpStatus - здесь нет статуса Delete, вместо него используется статус NO_CONTENT

2024-08-22 11:10 UTC, DanSBol commented on ewm-service/src/main/java/ru/practicum/explore/main/compilation/service/CompilationService.java
> +@AllArgsConstructor
Поправил

2024-08-22 11:22 UTC, DanSBol commented on ewm-service/src/main/java/ru/practicum/explore/main/compilation/service/CompilationService.java
> +    public CompilationDto createCompilation(NewCompilationDto newCompilationDto) {
Добавил

2024-08-22 11:27 UTC, DanSBol commented on ewm-service/src/main/java/ru/practicum/explore/main/event/dto/UpdateEventAdminRequest.java
> +    public enum State {
Поправил

2024-08-22 11:31 UTC, DanSBol commented on ewm-service/src/main/java/ru/practicum/explore/main/event/model/Event.java
> +    public enum State {
Поправил

2024-08-22 11:32 UTC, DanSBol commented on ewm-service/src/main/java/ru/practicum/explore/main/event/service/EventService.java
> +    public EventService(EventRepository eventRepository,
Поправил

2024-08-22 11:56 UTC, DanSBol commented on ewm-service/src/main/java/ru/practicum/explore/main/exceptions/NotFoundException.java
> +    public enum NotFoundType {
Поправил

2024-08-22 11:58 UTC, DanSBol commented on ewm-service/src/main/java/ru/practicum/explore/main/rating/model/Rating.java
> +    public static class RatingId implements Serializable {
Поправил

2024-08-23 05:09 UTC, ErkinKasymaliev approved these changes
привет, работа принята!

2024-08-23 06:53 UTC, merged